name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: team_OPsDnSSAZAsarDalcZAxI3NT
      VERCEL_PROJECT_ID: prj_7FnKea3UZi6mCRJF4q5KPQv898At

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel (build runs on Vercel servers)
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
